@MediatRApi_HostAddress = http://localhost:5000/api
@accessToken = Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiI2MWEyNzFkZC00ZmIzLTRmMmItYjY3My1iZTZmZTgwZDExOTUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdF91c2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3MDU3ODg2ODgsImlzcyI6IldlYkFwaUp3dC5jb20iLCJhdWQiOiJsb2NhbGhvc3QifQ.0-r0-TTDVuiotPizYSq9feFq_4XdILF2NpQZ1xFxx9Q

#name Checkout
POST {{MediatRApi_HostAddress}}/Checkouts/
Authorization: {{accessToken}}
Content-Type: application/json

{
    "Products" : [
        {
            "ProductId": "6VD2TkG1E0Z39mot",
            "Quantity": 10
        },
        {
            "ProductId": "yCNe2tMHAEONSbhm",
            "Quantity": 5
        }
    ]
}
