@MediatRApi_HostAddress = http://localhost:5000/api
@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJkMWQ2ZGRhZC0zNzQzLTRmZGQtYTMwMi1hOTI1NzA0ZmQxYWUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoib3RoZXJfdXNlciIsImV4cCI6MTcwMTg2OTI3MywiaXNzIjoiV2ViQXBpSnd0LmNvbSIsImF1ZCI6ImxvY2FsaG9zdCJ9.SwmyYDQWCzIwBilYxwhq3XAY2Q56ofz4yfwj32U0KRk
#name GetProducts
GET {{MediatRApi_HostAddress}}/products/
Accept: application/json
Authorization: {{accessToken}}

###

#name GetProductsById
GET {{MediatRApi_HostAddress}}/products/9ZeGz0FK
Accept: application/json
Authorization: {{accessToken}}

###

#name CreateProduct
POST {{MediatRApi_HostAddress}}/products/
Authorization: {{accessToken}}
Content-Type: application/json

{
  "description": "Product 05",
  "price": 50.50
}