@MediatRApi_HostAddress = http://localhost:5000/api

#name Token
POST {{MediatRApi_HostAddress}}/auth/
Content-Type: application/json

{
  "userName": "test_user",
  "password": "Passw0rd.1234"
}

###

#name Me
@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiJiMjQwNDRhMy0zN2QzLTQxOTctODZlMi1iM2E2MGU5MWYxNWEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdF91c2VyIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3MDM4NTIyMTEsImlzcyI6IldlYkFwaUp3dC5jb20iLCJhdWQiOiJsb2NhbGhvc3QifQ.APFe5g2sdosVki6LJgdQik3N0cZfOItgYrhPawIJ8oM
GET {{MediatRApi_HostAddress}}/auth/me
Accept: application/json
Authorization: {{accessToken}}